language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="57f7693a-5e0f-4916-8780-dfab59cabab4"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -commshepard@gmail.com
    on_success: never # default: change
    on_failure: always # default: always